cmd_drivers/net/wireless/rockchip_wlan/esp8089/esp_driver/spi_sif_esp.o := ../prebuilts/gcc/linux-x86/arm/arm-eabi-4.6/bin/arm-eabi-gcc -Wp,-MD,drivers/net/wireless/rockchip_wlan/esp8089/esp_driver/.spi_sif_esp.o.d  -nostdinc -isystem /home/skelton/xd/XD-EN-V335/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6/bin/../lib/gcc/arm-eabi/4.6.x-google/include -I/home/skelton/xd/XD-EN-V335/kernel/arch/arm/include -Iarch/arm/include/generated  -Iinclude -I/home/skelton/xd/XD-EN-V335/kernel/arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I/home/skelton/xd/XD-EN-V335/kernel/include/uapi -Iinclude/generated/uapi -include /home/skelton/xd/XD-EN-V335/kernel/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Os -Wno-maybe-uninitialized -fno-dwarf2-cfi-asm -mabi=aapcs-linux -mno-thumb-interwork -funwind-tables -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -fno-inline-functions-called-once -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DP2P_CONCURRENT -DESP_ACK_INTERRUPT -DESP_USE_SDIO -DDEBUG -DSIP_DEBUG -DFAST_TX_STATUS -DKERNEL_IV_WAR -DRX_SENDUP_SYNC -DHAS_FW -DTEST_MODE -DESP_ANDROID_LOGGER -DESP_PREALLOC -DESP_CLASS    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(spi_sif_esp)"  -D"KBUILD_MODNAME=KBUILD_STR(wlan)" -c -o drivers/net/wireless/rockchip_wlan/esp8089/esp_driver/spi_sif_esp.o drivers/net/wireless/rockchip_wlan/esp8089/esp_driver/spi_sif_esp.c

source_drivers/net/wireless/rockchip_wlan/esp8089/esp_driver/spi_sif_esp.o := drivers/net/wireless/rockchip_wlan/esp8089/esp_driver/spi_sif_esp.c

deps_drivers/net/wireless/rockchip_wlan/esp8089/esp_driver/spi_sif_esp.o := \

drivers/net/wireless/rockchip_wlan/esp8089/esp_driver/spi_sif_esp.o: $(deps_drivers/net/wireless/rockchip_wlan/esp8089/esp_driver/spi_sif_esp.o)

$(deps_drivers/net/wireless/rockchip_wlan/esp8089/esp_driver/spi_sif_esp.o):
