cmd_drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/rkversion.o := ../prebuilts/gcc/linux-x86/arm/arm-eabi-4.6/bin/arm-eabi-gcc -Wp,-MD,drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/.rkversion.o.d  -nostdinc -isystem /home/skelton/xd/XD-EN-V335/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6/bin/../lib/gcc/arm-eabi/4.6.x-google/include -I/home/skelton/xd/XD-EN-V335/kernel/arch/arm/include -Iarch/arm/include/generated  -Iinclude -I/home/skelton/xd/XD-EN-V335/kernel/arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I/home/skelton/xd/XD-EN-V335/kernel/include/uapi -Iinclude/generated/uapi -include /home/skelton/xd/XD-EN-V335/kernel/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Os -Wno-maybe-uninitialized -fno-dwarf2-cfi-asm -mabi=aapcs-linux -mno-thumb-interwork -funwind-tables -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -fno-inline-functions-called-once -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Wall -Wstrict-prototypes -Dlinux -DBCMDRIVER -DBCMDONGLEHOST -DUNRELEASEDCHIP -DBCMDMA32 -DWLBTAMP -DBCMFILEIMAGE -DDHDTHREAD -DDHD_DEBUG -DSDTEST -DBDC -DTOE -DDHD_BCMEVENTS -DSHOW_EVENTS -DBCMDBG -DMMC_SDIO_ABORT -DBCMSDIO -DBCMLXSDMMC -DBCMPLATFORM_BUS -DWIFI_ACT_FRAME -DARP_OFFLOAD_SUPPORT -DKEEP_ALIVE -DPKT_FILTER_SUPPORT -DGET_CUSTOM_MAC_ENABLE -DEMBEDDED_PLATFORM -DPNO_SUPPORT -DENABLE_INSMOD_NO_FW_LOAD -DDHD_USE_IDLECOUNT -DSET_RANDOM_MAC_SOFTAP -DVSDB -DWL_CFG80211_VSDB_PRIORITIZE_SCAN_REQUEST -DSDIO_CRC_ERROR_FIX -DESCAN_RESULT_PATCH -DHT40_GO -DPASS_ARP_PACKET -DSUPPORT_PM2_ONLY -DDHD_DONOT_FORWARD_BCMEVENT_AS_NETWORK_PKT -DAMPDU_HOSTREORDER -DCUSTOM_SDIO_F2_BLKSIZE=128 -DWL_SDO -DWLTDLS -DWL_SUPPORT_BACKPORTED_KPATCHES -Idrivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd -Idrivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/include -DCUSTOMER_HW -DSTATIC_WL_PRIV_STRUCT -DCONFIG_DHD_USE_STATIC_BUF -DENHANCED_STATIC_BUF -DOOB_INTR_ONLY -DHW_OOB -DCUSTOMER_OOB -DBAND_AG -DSOFTAP -DWL_WIRELESS_EXT -DUSE_IW -DWL_CFG80211 -DWLP2P -DWL_CFG80211_STA_EVENT -DCUSTOM_ROAM_TRIGGER_SETTING=-65 -DCUSTOM_ROAM_DELTA_SETTING=15 -DCUSTOM_KEEP_ALIVE_SETTING=28000 -DCUSTOM_PNO_EVENT_LOCK_xTIME=7 -DWL_SUPPORT_AUTO_CHANNEL    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(rkversion)"  -D"KBUILD_MODNAME=KBUILD_STR(bcmdhd)" -c -o drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/rkversion.o drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/rkversion.c

source_drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/rkversion.o := drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/rkversion.c

deps_drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/rkversion.o := \
    $(wildcard include/config/bcmdhd/fw/path.h) \
    $(wildcard include/config/bcmdhd/nvram/path.h) \

drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/rkversion.o: $(deps_drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/rkversion.o)

$(deps_drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/rkversion.o):
